name: Linux
on: workflow_call
jobs:
  BuildTestAndReportCoverage:
    runs-on: ubuntu-24.04
    env:
      CC: 'gcc-14'
      CXX: 'g++-14'
      GCOV: 'gcov-14'
      CXXFLAGS: '--coverage'
      LDFLAGS: '--coverage'
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
    steps:
      - name: Checkoout
        uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install missing toolchain tools
        run: sudo apt-get install --yes clang-tidy-18 libc++-18-dev ninja-build

      - name: Install dependencies & Configure
        run: cmake
          -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DCMAKE_CXX_CLANG_TIDY=clang-tidy-18
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Tests
        run: ctest --test-dir build --output-on-failure

      - name: Install gcovr
        run: |
          python3 -m venv python
          python/bin/pip install --upgrade pip
          python/bin/pip install gcovr

      - name: Run gcovr
        run: python/bin/gcovr
          --filter src
          --filter include
          --exclude-directories vcpkg
          --coveralls coveralls.json

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: coveralls
          file: coveralls.json
