name: Windows
on: workflow_call
jobs:
  BuildAndTest:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
    steps:
      - name: Checkoout
        uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install missing toolchain tools
        run: choco install ninja

      - name: Install dependencies & Configure
        run: cmake
          -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Tests
        run: ctest --test-dir build
